//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessData.DataAccess.SPA {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class QueryMap : global::System.Configuration.ApplicationSettingsBase {
        
        private static QueryMap defaultInstance = ((QueryMap)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QueryMap())));
        
        public static QueryMap Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT UNIDADE from Cursos;")]
        public string Faculdades {
            get {
                return ((string)(this["Faculdades"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT NOME, UNIDADE, CODIGO from Cursos;")]
        public string Cursos {
            get {
                return ((string)(this["Cursos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT PROFESSOR, MATRICULA, [CORREIO ELETRONICO] from Professores;")]
        public string Professores {
            get {
                return ((string)(this["Professores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT CODIGO, TURMA, CURSO, PROFESSOR1, HORARIO from Turmas WHERE PROFESSOR1 <> " +
            "\'none\'")]
        public string Turmas {
            get {
                return ((string)(this["Turmas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT CODIGO, CREDITOS, NOME, G2 FROM DISCIPLINAS")]
        public string Disciplinas {
            get {
                return ((string)(this["Disciplinas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT CODIGO, TURMA, CURSO, PROFESSOR1, HORARIO from Turmas where PROFESSOR1 = \'" +
            "none\';")]
        public string TurmasNone {
            get {
                return ((string)(this["TurmasNone"]));
            }
        }
    }
}
